AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - org.example::calculator
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  CalculatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.exercise.infrastructure.lambda.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  CalculatorApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/check-status'
    Export:
      Name: CalculatorApi
