name: Build and Deploy Lambdas

on:
  push:
    paths:
      - 'calculatorCreateOperation/**'
      - 'calculatorDeleteRecords/**'
      - 'calculatorListOperations/**'
      - 'calculatorListRecords/**'
      - 'calculatorLogin/**'
      - 'calculatorLogout/**'
      - 'calculatorSignup/**'
      - 'lambda-mapping.json'
      - '.github/workflows/deploy.yml'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Identificar diretório modificado
      - name: Identify changed directory
        id: detect-dir
        run: |
          echo "changed_dir=$(echo ${{ github.event.head_commit.message }} | grep -o 'backend[0-9]*')" >> $GITHUB_ENV

      # Step 3: Carregar o mapeamento do lambda
      - name: Load Lambda Mapping
        id: load-mapping
        run: |
          MAP=$(cat lambda-mapping.json)
          LAMBDA_NAME=$(echo $MAP | jq -r ".${{ env.changed_dir }}")
          echo "lambda_name=${LAMBDA_NAME}" >> $GITHUB_ENV

      # Step 4: Configurar Java e Maven
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Step 5: Build o backend
      - name: Build with Maven
        working-directory: ${{ env.changed_dir }}
        run: |
          mvn clean package -DskipTests -DfinalName=${{ env.changed_dir }}-artifact

      # Step 6: Configurar credenciais da AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      # Step 7: Fazer o zip do artefato
      - name: Zip the artifact
        working-directory: ${{ env.changed_dir }}
        run: zip -j ../${{ env.changed_dir }}-artifact.zip target/${{ env.changed_dir }}-artifact.jar

      # Step 8: Atualizar a Lambda
      - name: Update Lambda function
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.lambda_name }} \
            --zip-file fileb://${{ env.changed_dir }}-artifact.zip
