name: Build and Deploy Lambda

on:
  push:
    paths:
      - "calculatorCreateOperation/**"
      - "calculatorDeleteRecords/**"
      - "calculatorListOperations/**"
      - "calculatorListRecords/**"
      - "calculatorLogin/**"
      - "calculatorLogout/**"
      - "calculatorSignup/**"
      - "lambda-mapping.json"
      - ".github/workflows/deploy.yml"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Identify changed directory
        id: detect-dir
        run: |
          changed_dirs=$(git diff --name-only HEAD~1 HEAD | grep -oE '^calculator[^/]+/' | sort -u | head -n 1)
          echo "changed_dirs=$changed_dirs" >> $GITHUB_ENV

      - name: Validate JSON mapping
        run: jq . lambda-mapping.json > /dev/null

      - name: Load Lambda Mapping
        id: load-mapping
        run: |
          MAP=$(cat lambda-mapping.json)
          changed_dir=$(echo ${{ env.changed_dirs }} | tr -d '/')
          LAMBDA_NAME=$(echo $MAP | jq -r ".${changed_dir}")
          echo "lambda_name=${LAMBDA_NAME}" >> $GITHUB_ENV

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build with Maven
        working-directory: ${{ env.changed_dirs }}
        run: mvn clean package -DskipTests

      - name: Zip the Lambda artifact
        run: |
          zip -j lambda-artifact.zip ${{ env.changed_dirs }}/target/*.jar

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Update Lambda function
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.lambda_name }} \
            --zip-file fileb://lambda-artifact.zip
