name: Build and Deploy Lambdas

on:
  push:
    paths:
      - "calculatorCreateOperation/**"
      - "calculatorDeleteRecords/**"
      - "calculatorListOperations/**"
      - "calculatorListRecords/**"
      - "calculatorLogin/**"
      - "calculatorLogout/**"
      - "calculatorSignup/**"
      - "lambda-mapping.json"
      - ".github/workflows/deploy.yml"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Identify changed directory
        id: detect-dir
        run: |
          changed_dirs=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -oE '^calculator[^/]+/' | sort -u | sed 's:/$::')
          echo "changed_dir=${changed_dirs}" >> $GITHUB_ENV

      - name: Load Lambda Mapping
        id: load-mapping
        run: |
          MAP=$(cat lambda-mapping.json)
          echo "Mapping: $MAP" 
          LAMBDA_NAME=$(echo $MAP | jq -r ".${{ env.changed_dir }}")
          echo "lambda_name=${LAMBDA_NAME}" >> $GITHUB_ENV

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build with Maven
        working-directory: ${{ env.changed_dir }}
        run: |
          mvn clean package -DskipTests -DfinalName=${{ env.changed_dir }}-artifact

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Zip the artifact
        working-directory: ${{ env.changed_dir }}
        run: zip -j ../${{ env.changed_dir }}-artifact.zip target/${{ env.changed_dir }}-artifact.jar

      - name: Update Lambda function
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.lambda_name }} \
            --zip-file fileb://${{ env.changed_dir }}-artifact.zip
