name: Deploy Lambda

on:
  push:
    paths:
      - "calculatorCreateOperation/**"
      - "calculatorDeleteRecords/**"
      - "calculatorListOperations/**"
      - "calculatorListRecords/**"
      - "calculatorLogin/**"
      - "calculatorLogout/**"
      - "calculatorSignup/**"
      - "lambda-mapping.json"
      - ".github/workflows/deploy.yml"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Identify changed directory
        id: detect-dir
        run: |
          changed_dirs=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -oE '^calculator[^/]+/' | sort -u)
          echo "changed_dirs=$changed_dirs" >> $GITHUB_ENV

      - name: Load Lambda Mapping
        id: load-mapping
        run: |
          MAP=$(cat lambda-mapping.json)
          echo "Mapping loaded: $MAP"
          CHANGED_DIR=$(echo ${{ env.changed_dirs }} | sed 's#/##')
          echo "Changed directory: $CHANGED_DIR"
          LAMBDA_NAME=$(echo $MAP | jq -r ".${CHANGED_DIR}")
          if [ -z "$LAMBDA_NAME" ]; then
            echo "Error: Lambda mapping for directory '$CHANGED_DIR' not found."
            exit 1
          fi
          echo "lambda_name=${LAMBDA_NAME}" >> $GITHUB_ENV

      - name: Debug Variables
        run: |
          echo "Changed directory: ${{ env.changed_dirs }}"
          echo "Lambda name: ${{ env.lambda_name }}"

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: ${{ env.changed_dirs }}

      - name: Zip artifact
        run: |
          zip -j lambda-artifact.zip target/*.jar
        working-directory: ${{ env.changed_dirs }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Update Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.lambda_name }} \
            --zip-file fileb://lambda-artifact.zip
