name: Build and Deploy Lambda

on:
  push:
    paths:
      - "calculatorCreateOperation/**"
      - "calculatorDeleteRecords/**"
      - "calculatorListOperations/**"
      - "calculatorListRecords/**"
      - "calculatorLogin/**"
      - "calculatorLogout/**"
      - "calculatorSignup/**"
      - "lambda-mapping.json"
      - ".github/workflows/deploy.yml"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug changed files and directories
        run: |
          echo "Current branch: $(git branch --show-current)"
          echo "Files changed between origin/master and HEAD:"
          git diff --name-only origin/master HEAD
          changed_dirs=$(git diff --name-only origin/master HEAD | grep -oE '^calculator[^/]+' | sort -u)
          echo "Detected changed directories: ${changed_dirs}"
          if [ -z "$changed_dirs" ]; then
            echo "No directories detected. Exiting."
            exit 1
          fi
          echo "changed_dirs=${changed_dirs}" >> $GITHUB_ENV

      - name: Identify changed directories
        id: detect-dir
        run: |
          changed_dirs=$(git diff --name-only origin/master HEAD | grep -oE '^calculator[^/]+' | sort -u)
          echo "changed_dirs=${changed_dirs}" >> $GITHUB_ENV
          echo "Detected changed directories: ${changed_dirs}"

      - name: Validate JSON mapping
        run: jq . lambda-mapping.json > /dev/null

      - name: Load Lambda Mapping
        id: load-mapping
        run: |
          MAP=$(cat lambda-mapping.json)
          for dir in ${{ env.changed_dirs }}; do
            clean_dir=$(echo $dir | tr -d '/')
            LAMBDA_NAME=$(echo $MAP | jq -r ".${clean_dir}")
            if [ "$LAMBDA_NAME" != "null" ]; then
              echo "lambda_name=${LAMBDA_NAME}" >> $GITHUB_ENV
              echo "changed_dir=${dir}" >> $GITHUB_ENV
              break
            fi
          done

      - name: Debug changed directory and Lambda function
        run: |
          echo "Changed directory: ${{ env.changed_dir }}"
          echo "Lambda function: ${{ env.lambda_name }}"

      - name: Force a changed directory for testing
        run: |
          echo "Forcing changed_dirs to calculatorLogout/"
          echo "changed_dirs=calculatorLogout/" >> $GITHUB_ENV

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build with Maven
        working-directory: ${{ env.changed_dir }}
        run: mvn clean package -DskipTests

      - name: Zip the Lambda artifact
        run: |
          zip -j lambda-artifact.zip ${{ env.changed_dir }}/target/*.jar

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Update Lambda function
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.lambda_name }} \
            --zip-file fileb://lambda-artifact.zip
